### ISSUE TITLE
How to build and run?

### ISSUE THREAD

**Issue by nharmon9** [lightninglabs/neutrino#195] opened 2019-12-07 02:43 UTC

**Comment by yyforyongyu** [comment] 2019-12-09 09:43
I think `neutrino` is meant to be used as a package/library for now. As stated in the `README.md`,

> The client is instantiated as an object using `NewChainService` and then started.

**Comment by NotASithLord** [comment] 2020-02-10 20:19
Might still be useful for someone who wants to quickly see it in action from the command line if there's an easy path to doing so.

**Comment by halseth** [comment] 2020-02-11 08:31
Duplicate of https://github.com/lightninglabs/neutrino/issues/202

**Closed by halseth** 2020-02-11 08:31 UTC
