### ISSUE TITLE
Neutrino seems to be expecting a MsgReject when broadcasting a tx, but btcd does not reply to the INV

### ISSUE THREAD

**Issue by cjdelisle** [lightninglabs/neutrino#206] opened 2020-07-03 08:55 UTC
In order to decide when to stop rebroadcasting, [Broadcaster is expecting to see a MsgReject](https://github.com/lightninglabs/neutrino/blob/38bf97e348a3d89c8f473209abf811c64074e5b5/pushtx/broadcaster.go#L236). But I see that broadcaster calls cfg.Broadcast which ends in [ChainService.sendTransaction()](https://github.com/lightninglabs/neutrino/blob/39da434881572f823bee55994995a9e46fc985e9/query.go#L1118) and this is sending an INV message. On the btcd side, INV messages which are already known *in any way* are quietly ignored, as you can see in [SyncManager.handleInvMessage()](https://github.com/btcsuite/btcd/blob/96897255fd17525dd12426345d279533780bc4e1/netsync/manager.go#L1118) so unless I am mistaken, this idea of rebroadcasting until someone rejects as duplicate is not just non-ideal, it actually doesn't work in the normal case (unless bitcoind works differently, in which a case could be made that this is btcd's bug).

**Comment by Roasbeef** [comment] 2020-07-06 18:20
> this idea of rebroadcasting until someone rejects as duplicate is not just non-ideal, it actually doesn't work in the normal case (unless bitcoind works differently

Correct we added that just as a heuristic to know when to stop early . In reality, one should only stop rebroadcasting once the transaction has been confirmed in the chain.

**Comment by cjdelisle** [comment] 2020-07-10 12:19
Am I correct that the there is no code-path to tell Neutrino to *stop* broadcasting, except the one triggered by getting back a 'conflict' rejection ?   What I'm seeing is that broadcasts pile up forever, but I'm not sure if it is something I might have broken by my changes to the codebase.

**Comment by wpaulino** [comment] 2020-07-10 16:51
Correct. The broadcaster is stateless, on restart wallet transactions get queued. Ideally, we wait for the transaction to be included in a block to stop broadcasting, but that has yet to be done.

**Comment by halseth** [comment] 2020-07-17 11:45
Also must keep in mind that newer bitcoind versions will never send reject messages.

**Comment by Roasbeef** [comment] 2021-03-05 01:17
>  In reality, one should only stop rebroadcasting once the transaction has been confirmed in the chain.

Seems like we only need to implement this in order to close this gap?

**Comment by Roasbeef** [comment] 2021-05-18 22:36
@yaslama feel free to pick it up.

**Comment by kingonly** [comment] 2021-05-21 08:41
@Roasbeef this isn't an easy bug to pick up...
This should take a higher priority, shouldn't it? Seems like a serious bug and perhaps the title doesn't reflects its severity. Correct me if I'm wrong, but with the latest bitcoind, anyone using Neutrino to broadcast a tx, keeps broadcasting it forever, even if it's already confirmed.

**Comment by wpaulino** [comment] 2021-05-21 22:15
I took a quick look at how this could be implemented and it could definitely be non-trivial based on the approach taken. To make sure we detect transactions confirmed while offline, we'd have to keep track of a height hint for each transaction, as similarly done by the `ChainNotifier` in lnd. For the sake of improving neutrino as a standalone library (without the use of lnd), I think it would be best for it to follow that approach, either by integrating the `ChainNotifier` or replicating its behavior.

Given the severity of this issue affecting all neutrino lnd users, we could also go with a more trivial approach. All transactions broadcast by lnd go through its wallet. Since the wallet can already detect when a transaction confirms, we can provide a hook to cancel the transaction broadcast when running with a neutrino backend. The downside to this approach is that it wouldn't address the issue when neutrino is being used without lnd.

Thoughts?

**Comment by Roasbeef** [comment] 2021-05-21 23:23
Are all the rebroadcast attempts y'all re seeing transactions that pay solely to P2WSH outputs?

**Comment by yaslama** [comment] 2021-05-23 08:10
@Roasbeef we have cases where we broadcast using lnd api transactions with output given by the user, so we cannot make any assumptions about the output.
@wpaulino in Breez, we launch neutrino from time to time as a background job, so the first solution is better for us.

**Comment by cjdelisle** [comment] 2021-05-23 08:19
I ended up fixing this for my own purposes via https://github.com/pkt-cash/pktd/blob/master/neutrino/query.go#L1551 which might be back-portable but I never pursued backporting any of the changes I made because, quite frankly, I changed a lot of design decisions and deleted a lot of code. But maybe someone will find some of it useful...

**Comment by wpaulino** [comment] 2021-05-26 18:41
> we have cases where we broadcast using lnd api transactions with output given by the user, so we cannot make any assumptions about the output.
in Breez, we launch neutrino from time to time as a background job, so the first solution is better for us. But the second solution is more than ok.

@yaslama since all the transactions are sourced from lnd's wallet, launching neutrino as a standalone background process will not broadcast any transactions on its own.

I'll be working on addressing the continuous broadcast issue for neutrino lnd users (see my previous comment) some time throughout the lnd v0.14 cycle.

**Comment by kingonly** [comment] 2021-05-26 21:03
Much appreciated @wpaulino 🙏

**Comment by yaslama** [comment] 2021-05-26 22:00
> I'll be working on addressing the continuous broadcast issue for neutrino lnd users (see my previous comment) some time throughout the lnd v0.14 cycle.
Thanks a lot @wpaulino

**Comment by Roasbeef** [comment] 2021-07-28 00:23
> I think it would be best for it to follow that approach, either by integrating the ChainNotifier or replicating its behavior.

Yeah I think the best option here is to have the rescan logic inherit some call back, so it can speak to rebroadcaster to let it know when something eventually gets confirmed or not.

**Closed** 2021-09-28 00:59 UTC
Labels: bug, P2
